### ISSUE TITLE
Allow psr/http-message v2

### ISSUE THREAD

**Issue by ruerdev** [crwlrsoft/url#41]
Hi!

I just tried to install this package in a fresh Laravel application, but was greeted by the message that it could not satisfy my composer lock file, as the psr/http-message package was locked at v2 and this package only allows v1.

When I look at the release notes, it should be fine to include v2 as well. Other packages seem to support both v1 and v2 at the same time.
<img width="613" alt="Scherm­afbeelding 2023-06-28 om 14 27 52" src="https://github.com/crwlrsoft/url/assets/25254145/c08a1452-5616-4ec4-9ccc-1c3acdfaaefe">

I can lock the psr/http-message to v1 in my project, but I think it will be better to follow the latest releases.

Would be great if this is possible.

**Comment by otsch** [comment]
Hey @ruerdev 👋
thanks for the hint! I just upgraded the version constraint to `^1.0 || ^2.0` in https://github.com/crwlrsoft/url/releases/tag/v2.0.4 
Hope you'll like the package! 🙂

**Comment by ruerdev** [comment]
@otsch Thanks, that was really fast! I'm loving the crawler package so far, amazing work :)
